// Generated by https://quicktype.io

class Versiculo {
  String texto;

  Versiculo({
    this.texto,
  });

  Versiculo.fromJsonMap( Map< String, dynamic> json ) {
    texto = json[ 'text' ];
  }
}
